name: stochastic-payoffs
channels:
  - defaults
dependencies:
  - pip=20.2.2
  - python=3.7.9
  - setuptools=49.6.0
  - pip:
    - black==20.8b1
    - blackbook==0.0.6
    - jupyter==1.0.0
    - numpy==1.19.1
    - pytest==6.0.1
    - pytest-cov==2.10.1
    - sympy==1.6.2