name: TESTS

on:
  push:
  pull_request:

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/checkout@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -r requirements.txt
        python setup.py develop
    - name: Install testing dependencies
      run: |
        python -m pip install pytest
        python -m pip install pytest-cov
        python -m pip install black
        python -m pip install isort
    - name: Lint with Black
      if: matrix.python-version == 3.7 && matrix.os == 'ubuntu-latest'
      run: |
        python -m black --check --diff -l 80 .
    - name: Lint imports with isort
      if: matrix.python-version == 3.7 && matrix.os == 'ubuntu-latest'
      run: |
        python -m isort -w 80 -m 3 --trailing-comma --check-only .
    - name: Test with pytest 
      run: |
        python -m pytest --cov-report term-missing --cov=src --cov-fail-under=100 tests
